### ISSUE TITLE
Consuming jobs in a finer granularity

### ISSUE THREAD

**Issue by jaywonchung** [jaywonchung/pegasus#5]
```yaml
# queue.yaml
- command:
    - long_job {{ param }}
    - another_long_job {{ param }}
  param:
    - resnet50
    - ViT
```

Currently, Pegasus will consume the entire entry (virtually the entire file) from `queue.yaml`. However, consuming minimally would be nice. For instance, leaving `queue.yaml` in the following state would be nice:

```yaml
# queue.yaml
- command:
    - another_long_job {{ param }}
   param:
    - resnet50
    - ViT
```

Then in the next round of `get_one_job`, only then `queue.yaml` will be empty.
